name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release to npm
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test -- --run
        env:
          LODGIFY_API_KEY: test-api-key
          TEST_MODE: mock
      
      - name: Build
        run: npm run build
      
      - name: Verify package
        run: |
          npm pack --dry-run
          echo "Package contents:"
          npm pack --dry-run 2>/dev/null | grep -v "npm notice"
      
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            lodgify-mcp-*.tgz
          generate_release_notes: true
          body: |
            ## Lodgify MCP Server ${{ github.ref_name }}
            
            ### Installation
            ```bash
            npm install lodgify-mcp@${{ github.ref_name }}
            ```
            
            ### What's Changed
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
            
            ### Full Changelog
            https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}